dist: xenial

language: go
go:
 - 1.10.3
 - tip

# Looks like 'dep' isn't in the zenial PPAs
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

# TODO: do non-draft releases and cross-platform releases
jobs:
 include:
  - script: make test
  - script: make build
  - stage: deploy
    script: ls; pwd
    go: 1.10.3
    deploy:
     provider: releases
     api_key: $RELEASES_TOKEN
     prerelease: true
     on:
      branch: master
     file:
      - proxy-server