dist: xenial

language: go
go:
 - 1.12.5
 - tip

# Looks like 'dep' isn't in the zenial PPAs - sadly this is the recommended installation procedure
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - make test
  - make build

# TODO: do non-draft releases and cross-platform releases
jobs:
 include:
  - stage: deploy
    go: 1.12.5
    before_deploy:
      - ls; pwd
    deploy:
     provider: releases
     api_key: $RELEASES_TOKEN
     prerelease: true
     skip_cleanup: true # Without this the build artifacts are cleaned up before deploy!
     on:
      branch: master
     file:
      - "proxy-server"
